# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TZcKgSXRIJWREudlTfX9NcyTwLEYlHD
"""

!pip install transformers accelerate bitsandbytes --quiet


import random
import numpy as np
torch.manual_seed(42)
random.seed(42)
np.random.seed(42)

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

def load_4bit_model(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto",
        torch_dtype=torch.float16,
        load_in_4bit=True
    )
    return tokenizer, model

member_names = [
    "ibm-granite/granite-3.3-2b-instruct",
    "ibm-granite/granite-3.3-2b-instruct",
    "ibm-granite/granite-3.3-2b-instruct"
]

members = []
for name in member_names:
    tok, mod = load_4bit_model(name)
    members.append((tok, mod))

chairman_name = "meta-llama/Llama-3.2-3B-Instruct"
chair_tok, chair_model = load_4bit_model(chairman_name)

def generate(model, tokenizer, prompt, max_tokens=256, temperature=0.7):
    inputs = tokenizer(prompt, return_tensors="pt").to(DEVICE)
    output = model.generate(
        **inputs,
        max_new_tokens=max_tokens,
        do_sample=True,
        temperature=temperature
    )
    return tokenizer.decode(output[0], skip_special_tokens=True)

def run_council(patient_case):

    agenda = patient_case.strip()


    member_outputs = []
    for i, (tok, model) in enumerate(members):
        prompt = f"""
You are Council Member {i+1}.
Patient case: {agenda}

Provide:
1. List possible diagnoses
2. Suggest initial investigations
3. Explain reasoning step by step
4. Give a concise final answer
"""
        ans = generate(model, tok, prompt, max_tokens=256, temperature=0.8)
        member_outputs.append(ans)


    synthesis_prompt = f"""
You are the chairman. Below are 3 member responses to a single patient case:

Case:
{agenda}

Member Responses:
1. {member_outputs[0]}
2. {member_outputs[1]}
3. {member_outputs[2]}

Tasks:
1. Identify any errors or hallucinations in the responses
2. Rank the responses by reasoning quality
3. Provide a single concise final answer based on the best reasoning
"""
    final_answer = generate(chair_model, chair_tok, synthesis_prompt, max_tokens=300, temperature=0.2)

    return member_outputs, final_answer

patient_case = """
A 60-year-old female with a history of hypertension and hyperlipidemia
presents with sudden onset severe chest pain radiating to the left arm,
diaphoresis, and shortness of breath. The patient is tachycardic and hypotensive.
What is the differential diagnosis? What initial investigations should be ordered?
"""

members_out, final_out = run_council(patient_case)

print("=== Member Outputs ===")
for i, m in enumerate(members_out):
    print(f"\nMember {i+1}:\n{m}")

print("\n=== Chairman Final Answer ===")
print(final_out)